In [265]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [266]:
import pandas as pd

fake = pd.read_csv("/content/train.csv")


In [267]:
fake

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [268]:
fake.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [269]:
fake.tail()

id                                              title  \
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1

In [270]:
fake.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [271]:
fake.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [272]:
fake.shape

(20800, 5)

In [273]:
fake.size

104000

In [274]:
fake_news=fake.dropna()

In [275]:
fake_news

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [276]:
fake_news.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [277]:
X=fake_news.drop("label",axis=1)

In [278]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [279]:
y=fake_news["label"]

In [280]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [281]:
X.shape

(18285, 4)

In [282]:
y.shape

(18285,)

In [283]:
import tensorflow as tf

from tensorflow.keras.layers import Embedding                     # Helps us to implement word2vec
from tensorflow.keras.preprocessing.sequence import pad_sequences         # Pre & Post padding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [284]:
# Assigning the value size to the vocabulary
vocabulary_size=5000

One Hot Encoding will take the text data into a vector form and do the feature representation on the data, Where the vocabulary size is 5000 in our case,the words in the data it will arrange the position as per vocabulary size.

# **One-Hot Encoding Representation**

In [285]:
message=X.copy()

In [286]:
message

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [287]:
message["title"]

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: title, Length: 18285, dtype: object

In [288]:
message.reset_index(inplace=True)

In [289]:
message

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

# **Let's Clean the Text Data ⏺**

In [290]:
import nltk
import re
from nltk.corpus import stopwords

In [291]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [292]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose to implement the sentimental analysis
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [293]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

One - Hot Representation

In [294]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [295]:
onehot_rep=[one_hot(words,vocabulary_size) for words in corpus]

In [296]:
onehot_rep

[[2804, 242, 3905, 4420, 542, 1014, 2206, 970, 4050, 2780],
 [1204, 3975, 3524, 2887, 1399, 4779, 3197],
 [1377, 1471, 417, 177],
 [205, 1926, 865, 1948, 688, 1574],
 [992, 1399, 3573, 1235, 1513, 1238, 1399, 2318, 237, 992],
 [1263,
  525,
  1364,
  3269,
  682,
  1510,
  338,
  3978,
  2773,
  947,
  4154,
  2811,
  343,
  1202,
  3197],
 [2358, 897, 4309, 4232, 4206, 2042, 367, 3759, 1730, 624, 2894],
 [2565, 1564, 611, 3731, 776, 1731, 1510, 4701, 1730, 624, 2894],
 [4001, 738, 2617, 1791, 1276, 4432, 1661, 3945, 1510, 1194],
 [4767, 4030, 3100, 2802, 1845, 4057, 1475, 2429],
 [3399, 972, 4514, 3584, 4839, 4704, 3146, 3016, 353, 3604, 2446],
 [1948, 2653, 542, 4432, 1510, 776],
 [3272, 2854, 3400, 852, 4833, 639, 2179, 2258, 1514],
 [4560, 583, 3114, 4021, 2027, 2697, 3416, 1730, 624, 2894],
 [4698, 3883, 4280, 2959, 581, 1730, 624, 2894],
 [3865, 1212, 4237, 4983, 2350, 260, 462, 858, 2903, 3807],
 [2625, 1153, 3975],
 [167, 4290, 1601, 4052, 1510, 4230, 1244, 3197],
 [4168, 3038,

In [297]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [298]:
onehot_rep[1]

[1204, 3975, 3524, 2887, 1399, 4779, 3197]

Embedding Representation

In [299]:
sentence_length=20
embedded_doc=pad_sequences(onehot_rep,padding="pre",maxlen=sentence_length)

In [300]:
print(embedded_doc)

[[   0    0    0 ...  970 4050 2780]
 [   0    0    0 ... 1399 4779 3197]
 [   0    0    0 ... 1471  417  177]
 ...
 [   0    0    0 ... 1730  624 2894]
 [   0    0    0 ... 3887 2182 1672]
 [   0    0    0 ... 1898 1422  307]]


In [301]:
embedded_doc[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 1204, 3975, 3524, 2887, 1399, 4779, 3197], dtype=int32)

In [302]:
embedded_doc

array([[   0,    0,    0, ...,  970, 4050, 2780],
       [   0,    0,    0, ..., 1399, 4779, 3197],
       [   0,    0,    0, ..., 1471,  417,  177],
       ...,
       [   0,    0,    0, ..., 1730,  624, 2894],
       [   0,    0,    0, ..., 3887, 2182, 1672],
       [   0,    0,    0, ..., 1898, 1422,  307]], dtype=int32)

# **Creating the Model and Applying the LSTM & Embedding Layers ❤**

In [303]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(vocabulary_size,embedding_vector_features,input_length=sentence_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation="sigmoid"))
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional_2 (Bidirecti  (None, 200)               112800    
 onal)                                                           
                                                                 
 dense_6 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313001 (1.19 MB)
Trainable params: 313001 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [304]:
len(embedded_doc),y.shape

(18285, (18285,))

In [305]:
X_final=np.array(embedded_doc)
y_final=np.array(y)

In [306]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [307]:
# Splitting the data into training & Testing
from sklearn.model_selection import train_test_split


In [308]:
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,test_size=0.30,random_state=45)


In [309]:
# Model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=40)

Epoch 1/10
320/320 [==============================] - 21s 53ms/step - loss: 0.2793 - accuracy: 0.8687 - val_loss: 0.1953 - val_accuracy: 0.9185
Epoch 2/10
320/320 [==============================] - 15s 46ms/step - loss: 0.1357 - accuracy: 0.9470 - val_loss: 0.1889 - val_accuracy: 0.9225
Epoch 3/10
320/320 [==============================] - 14s 45ms/step - loss: 0.0812 - accuracy: 0.9708 - val_loss: 0.2637 - val_accuracy: 0.9176
Epoch 4/10
320/320 [==============================] - 15s 48ms/step - loss: 0.0517 - accuracy: 0.9841 - val_loss: 0.2788 - val_accuracy: 0.9205
Epoch 5/10
320/320 [==============================] - 14s 45ms/step - loss: 0.0306 - accuracy: 0.9905 - val_loss: 0.3076 - val_accuracy: 0.9205
Epoch 6/10
320/320 [==============================] - 14s 45ms/step - loss: 0.0175 - accuracy: 0.9944 - val_loss: 0.4086 - val_accuracy: 0.9138
Epoch 7/10
320/320 [==============================] - 14s 45ms/step - loss: 0.0121 - accuracy: 0.9966 - val_loss: 0.4467 - val_accuracy:

In [310]:
# Predicting the model
y_pred=model.predict(X_test)


172/172 [==============================] - 2s 7ms/step


In [311]:
y_pred=np.where(y_pred>0.5,1,0)

In [312]:
from sklearn.metrics import confusion_matrix

In [313]:
confusion_matrix(y_test,y_pred)

array([[2875,  258],
       [ 212, 2141]])

In [314]:
from sklearn.metrics import accuracy_score

In [315]:
accuracy_score(y_test,y_pred)

0.914327378782355

In [316]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92      3133
           1       0.89      0.91      0.90      2353

    accuracy                           0.91      5486
   macro avg       0.91      0.91      0.91      5486
weighted avg       0.91      0.91      0.91      5486

